################################################################################
# Judge0 Configuration
################################################################################

# Sandbox settings — required for isolate to work properly
RAILS_ENV=production

# Workers
INTERVAL=0.1
MAINTENANCE_MODE=false

# Timeouts
CPU_TIME_LIMIT=5
CPU_EXTRA_TIME=1
WALL_TIME_LIMIT=10
MEMORY_LIMIT=128000
STACK_LIMIT=64000
MAX_PROCESSES_AND_OR_THREADS=30
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=false
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=false
MAX_FILE_SIZE=1024
NUMBER_OF_RUNS=1

# Submission limits
MAX_QUEUE_SIZE=100
